name: Nightly Build (Custom Kernel)

on:
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout pmos Repositories
        uses: actions/checkout@v4
        with:
          repository: postmarketOS/pmbootstrap # You might still need pmbootstrap
          path: pmbootstrap

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends git make gcc bc bison flex libncurses5-dev libssl-dev

      - name: Checkout Custom Kernel
        uses: actions/checkout@v4
        with:
          repository: WiiPlayer2/linux-sm7150
          ref: 2025-04-03 # Or your desired branch
          path: kernel

      - name: Checkout Device Specific Files
        uses: actions/checkout@v4
        with:
          repository: a71-pmos/pmaports-a71
          ref: device/samsung-a71 # Assuming this is the correct branch
          path: pmaports-a71

      - name: Prepare Kernel Configuration
        run: |
          cd kernel
          cp arch/arm64/configs/sm7150.config .config
          make defconfig

      - name: Integrate Device Specific Kernel Patches (Example - Adapt as needed)
        run: |
          cd kernel
          # Assuming you have patches in your pmaports-a71 fork
          # git apply ../pmaports-a71/path/to/your/patches/*.patch

      - name: Build Kernel
        run: |
          cd kernel
          make -j$(nproc)

      - name: Build Modules
        run: |
          cd kernel
          make modules -j$(nproc)

      - name: Set up pmbootstrap Environment
        run: |
          cd pmbootstrap
          ./pmbootstrap.sh init # You might need to adjust this if already initialized

      - name: Build pmos Image
        run: |
          cd pmbootstrap
          ./pmbootstrap.sh build --device samsung-a71 --kernel-dir ../kernel --extra-fde # Add other options as needed

      - name: Upload Artifacts (Example - Adjust as needed)
        uses: actions/upload-artifact@v3
        with:
          name: pmos-image-samsung-a71
          path: pmbootstrap/deploy/samsung-a71-*